In [33]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

from pandas.plotting import scatter_matrix

In [34]:
# ustawienie stylu wykresów
plt.style.use('classic') 
sns.set()

# ustawienie maksymalnej liczby wyświetlanych kolumn w DataFrame
pd.set_option('display.max_columns', 100)

In [35]:
df = pd.read_csv("dataset.csv", low_memory=False)

In [36]:
df.columns

Index(['ts', 'uid', 'id.orig_h', 'id.orig_p', 'id.resp_h', 'id.resp_p',
       'proto', 'service', 'duration', 'orig_bytes', 'resp_bytes',
       'conn_state', 'local_orig', 'local_resp', 'missed_bytes', 'history',
       'orig_pkts', 'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes',
       'tunnel_parents', 'ip_proto', 'trans_depth', 'method', 'host', 'uri',
       'referrer', 'version', 'user_agent', 'origin', 'request_body_len',
       'response_body_len', 'status_code', 'status_msg', 'info_code',
       'info_msg', 'tags', 'username', 'password', 'proxied', 'orig_fuids',
       'orig_filenames', 'orig_mime_types', 'resp_fuids', 'resp_filenames',
       'resp_mime_types'],
      dtype='object')

In [37]:
df.head()

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto,trans_depth,method,host,uri,referrer,version,user_agent,origin,request_body_len,response_body_len,status_code,status_msg,info_code,info_msg,tags,username,password,proxied,orig_fuids,orig_filenames,orig_mime_types,resp_fuids,resp_filenames,resp_mime_types
0,2026-05-07 17:23:36.378462076,CjVaJ01rkSFRPnrlE2,fe80::a042:4eff:fe28:b79e,143,ff02::16,0,icmp,NaN,NaN,NaN,NaN,OTH,T,F,0.0,NaN,1.0,76.0,0.0,0.0,NaN,58.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-05-07 17:23:36.509337901,CDraIq46By2DpQzft3,172.30.0.141,43566,172.30.0.40,80,tcp,http,0 days 00:00:58.665282,564.0,0.0,S1,T,T,0.0,ShADa,15.0,1352.0,14.0,736.0,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-05-07 17:23:36.509452105,CDraIq46By2DpQzft3,172.30.0.141,43566,172.30.0.40,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,POST,target_nginx,/rudy,TESTING_PURPOSES_ONLY,NaN,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2)...,NaN,84.0,0.0,NaN,NaN,NaN,NaN,(empty),NaN,NaN,NaN,FfVP7o2kH2iJLxH1c3,NaN,text/plain,NaN,NaN,NaN
3,2026-05-07 17:23:36.843274117,CgB9RJtCNNZ6k0bch,172.30.0.141,43574,172.30.0.40,80,tcp,http,0 days 00:00:58.331358,557.0,0.0,S1,T,T,0.0,ShADa,15.0,1345.0,14.0,736.0,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-05-07 17:23:36.843389988,CgB9RJtCNNZ6k0bch,172.30.0.141,43574,172.30.0.40,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,POST,target_nginx,/rudy,TESTING_PURPOSES_ONLY,NaN,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2)...,NaN,77.0,0.0,NaN,NaN,NaN,NaN,(empty),NaN,NaN,NaN,F3Dz94XlWRshkh5zc,NaN,text/plain,NaN,NaN,NaN

In [38]:
df.describe()

,id.orig_p,id.resp_p,orig_bytes,resp_bytes,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto,trans_depth,version,origin,request_body_len,response_body_len,status_code,info_code,info_msg,username,password,proxied,orig_filenames,resp_filenames
count,78043.000000,78043.000000,37342.000000,3.734200e+04,37345.000000,37345.000000,37345.000000,37345.000000,3.734500e+04,0.0,37345.000000,40698.000000,3.198000e+04,0.0,40698.000000,4.069800e+04,31980.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,47422.279141,3706.410056,262.511060,2.033066e+04,0.098005,8.759298,724.840514,8.228170,2.080672e+04,NaN,6.001392,1.612069,1.100000e+00,NaN,33.950931,1.774475e+04,205.621639,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,8304.757508,3982.542161,326.054609,9.275477e+04,18.918644,11.436551,747.796388,16.564161,9.390920e+04,NaN,0.269084,1.599547,6.579285e-13,NaN,70.437464,8.777830e+04,33.849993,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,143.000000,0.000000,0.000000,0.000000e+00,0.000000,1.000000,52.000000,0.000000,0.000000e+00,NaN,6.000000,1.000000,1.100000e+00,NaN,0.000000,0.000000e+00,200.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,39515.000000,80.000000,147.000000,0.000000e+00,0.000000,4.000000,467.000000,4.000000,2.160000e+02,NaN,6.000000,1.000000,1.100000e+00,NaN,0.000000,5.610000e+02,200.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,47240.000000,80.000000,166.000000,3.509000e+03,0.000000,7.000000,538.000000,5.000000,3.673000e+03,NaN,6.000000,1.000000,1.100000e+00,NaN,0.000000,3.345000e+03,200.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,55202.000000,8080.000000,294.000000,3.520000e+03,0.000000,7.000000,706.000000,5.000000,3.788000e+03,NaN,6.000000,1.000000,1.100000e+00,NaN,0.000000,3.345000e+03,200.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,60998.000000,8080.000000,3925.000000,1.814075e+06,3656.000000,164.000000,8734.000000,276.000000,1.828323e+06,NaN,58.000000,14.000000,1.100000e+00,NaN,305.000000,1.812480e+06,500.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
df["id.orig_h"].unique()

array(['fe80::a042:4eff:fe28:b79e', '172.30.0.141', '172.30.0.40',
       '172.30.0.10', '172.30.0.73', '172.30.0.87', '172.30.0.239',
       '172.30.0.137', '172.30.0.241', '172.30.0.123', '172.30.0.164',
       '172.30.0.167', '172.30.0.129', '172.30.0.19', '172.30.0.57'],
      dtype=object)

In [40]:
attack_path = "container_results.json"   # change if needed

try:
    # JSONL format (recommended)
    attack_df = pd.read_json(attack_path, lines=True)
except ValueError:
    # fallback: normal JSON array
    attack_df = pd.read_json(attack_path)


ip_to_label = attack_df.set_index("ip")["attack_type"].to_dict()



df["label"] = df["id.orig_h"].map(ip_to_label)

df["label"] = df["label"].fillna(
    df["id.resp_h"].map(ip_to_label)
)

df["label"] = df["label"].fillna("normal")


df["binary_label"] = (df["label"] != "normal").astype(int)


print("Done. Saved: dataset_labeled.csv")
print(df["label"].value_counts())

Done. Saved: dataset_labeled.csv
label
normal       72901
slowloris     2720
rudy          1789
slowread       633
Name: count, dtype: int64

In [42]:
df.head()

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto,trans_depth,method,host,uri,referrer,version,user_agent,origin,request_body_len,response_body_len,status_code,status_msg,info_code,info_msg,tags,username,password,proxied,orig_fuids,orig_filenames,orig_mime_types,resp_fuids,resp_filenames,resp_mime_types,label,binary_label
0,2026-05-07 17:23:36.378462076,CjVaJ01rkSFRPnrlE2,fe80::a042:4eff:fe28:b79e,143,ff02::16,0,icmp,NaN,NaN,NaN,NaN,OTH,T,F,0.0,NaN,1.0,76.0,0.0,0.0,NaN,58.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal,0
1,2026-05-07 17:23:36.509337901,CDraIq46By2DpQzft3,172.30.0.141,43566,172.30.0.40,80,tcp,http,0 days 00:00:58.665282,564.0,0.0,S1,T,T,0.0,ShADa,15.0,1352.0,14.0,736.0,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rudy,1
2,2026-05-07 17:23:36.509452105,CDraIq46By2DpQzft3,172.30.0.141,43566,172.30.0.40,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,POST,target_nginx,/rudy,TESTING_PURPOSES_ONLY,NaN,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2)...,NaN,84.0,0.0,NaN,NaN,NaN,NaN,(empty),NaN,NaN,NaN,FfVP7o2kH2iJLxH1c3,NaN,text/plain,NaN,NaN,NaN,rudy,1
3,2026-05-07 17:23:36.843274117,CgB9RJtCNNZ6k0bch,172.30.0.141,43574,172.30.0.40,80,tcp,http,0 days 00:00:58.331358,557.0,0.0,S1,T,T,0.0,ShADa,15.0,1345.0,14.0,736.0,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rudy,1
4,2026-05-07 17:23:36.843389988,CgB9RJtCNNZ6k0bch,172.30.0.141,43574,172.30.0.40,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,POST,target_nginx,/rudy,TESTING_PURPOSES_ONLY,NaN,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2)...,NaN,77.0,0.0,NaN,NaN,NaN,NaN,(empty),NaN,NaN,NaN,F3Dz94XlWRshkh5zc,NaN,text/plain,NaN,NaN,NaN,rudy,1

In [ ]:
df.to_csv("dataset_labeled.csv", index=False)